"""Update users table

Revision ID: 0c1e5bc15848
Revises: 846a8bae2acc
Create Date: 2023-12-10 21:18:02.190522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c1e5bc15848'
down_revision = '846a8bae2acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
